### GET
GET http://localhost:8000

### POST
POST http://localhost:8000/post/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "hello"
}

### GET all donations
GET http://localhost:8000/get/donationItems

### POST
POST http://localhost:8000/post/donationItem
Content-Type: application/json

{
    "name": "Refrigertor Samsung",
    "description": "Refrigertor Samsung 2019 model in good condition with a shelf for storing food. The ice box is not working but everything else is working. There are a few scratches",
    "category": "Electronics",
    "imageUrl": "https://images.unsplash.com/photo-1581091019745-0d5b8b6a4b0e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVmcmlnZXJ0b3IlMjBzb21ldGhpbmd8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
    "useability": 0.9,
    "price": 888.8,
    "itemWidth": 500.2,
    "itemHeight": 100,
    "itemLength": 800,
    "weight": 1000,
    "tags": ["fridge", "samsung", "icebox", "refrigertor"],
    "deliveryFees": 700,
    "deliveryPaidBy": "donor",
    "donorName": "John Doe",
    "usedDuration": 2,
    "isGiven": false,
    "authorId": "60b9b5b9e4b0f3b2a8b0b3a0",
    "authorName": "John Doe",
    "authorImageURL": "https://images.unsplash.com/photo-1581091019745-0d5b8b6a4b0e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVmcmlnZXJ0b3IlMjBzb21ldGhpbmd8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80"
}

### POST (change id everytime you post)
POST http://localhost:8000/post/users/testid1
Content-Type: application/json

{
   "userName": "Note",
   "userPhoneNumber": "0894499153",
   "profilePicture": "https://images.unsplash.com/photo-1581091019745-0d5b8b6a4b0e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVmcmlnZXJ0b3IlMjBzb21ldGhpbmd8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
   "userAddress": "122 Wattana nakorkorn",
   "blockedUser": [],
   "discountCoupon": [],
   "userOwnPost": [],
   "userReviewPost":[],
   "coverPicture": "",
   "token": ""
}


### PUT
PUT http://localhost:8000/put/users/vY9xlAikX2RnpXG6JpuV1zZbIQq1
Content-Type: application/json

{
  "userName": "Updated Name",
  "userPhoneNumber": "1234567890",
  "userAddress": "New Address"
}

### GET
GET http://localhost:8000/get/users/vY9xlAikX2RnpXG6JpuV1zZbIQq1

### POST 

POST http://localhost:8000/post/review
Content-Type: application/json

{
  "itemName": "Chair",
  "donorName": "Thomas Shelby",
  "receiverName": "James Shelby",
  "itemImage": "",
  "rating": 0,
  "price": 0,
  "usability": 0,
  "usedDuration": 0,
  "reviewText": "James loves this chair."
}

