// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk_88xqRGFeFhSLQ5POsA2h5CTGzrPd9w',
    appId: '1:976116118616:web:7e9dbc7641b7c73e21862d',
    messagingSenderId: '976116118616',
    projectId: 'sahara-9a91b',
    authDomain: 'sahara-9a91b.firebaseapp.com',
    storageBucket: 'sahara-9a91b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWRs72M1aBrxRCjtykAZ3bfNAm2IhCrY',
    appId: '1:976116118616:android:e4fd84db940f59a021862d',
    messagingSenderId: '976116118616',
    projectId: 'sahara-9a91b',
    storageBucket: 'sahara-9a91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGA5gd9QWMCiINhX0Vo4Uu5Akvp70UE8',
    appId: '1:976116118616:ios:3d3126e6fab56e5c21862d',
    messagingSenderId: '976116118616',
    projectId: 'sahara-9a91b',
    storageBucket: 'sahara-9a91b.appspot.com',
    iosClientId: '976116118616-j1t8rde9h2c42018heu75rareo3vnvf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahara',
  );
}
